/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.anseranser;

import ru.anseranser.model.Game;

public class App {

    public static void main(String[] args) {
        Game game = new Game();
        game.playGame();
    }
}
