/* This source file was generated by the Gradle 'init' task (entry point wired to listener/input in refactor Stage 1) */
package ru.anseranser;

import ru.anseranser.event.ConsoleGameListener;
import ru.anseranser.event.GameListener;
import ru.anseranser.input.ConsoleInputProvider;
import ru.anseranser.input.InputProvider;
import ru.anseranser.model.Game;
import ru.anseranser.model.HumanPlayer;
import ru.anseranser.model.Player;

public class App {

    public static void main(String[] args) {
        boolean humanPlayer = true;
        Game game = new Game(humanPlayer);

        GameListener listener = new ConsoleGameListener();
        game.setListener(listener);

        if (humanPlayer) {
            InputProvider input = new ConsoleInputProvider();
            for (Player p : game.getPlayers()) {
                if (p instanceof HumanPlayer human) {
                    human.setInput(input);
                }
            }
        }

        game.playGame();
    }
}
